import { FormularioDatos } from './formulario.model';

export const createFormularioDefaults = (): FormularioDatos => ({
  projectName: '',
  grupoAISD: '',
  grupoAISI: '',
  departamentoSeleccionado: '',
  provinciaSeleccionada: '',
  distritoSeleccionado: '',
  detalleProyecto: '',
  aisdComponente1: '',
  aisdComponente2: '',
  aisiComponente1: '',
  aisiComponente2: '',
  seleccionados: [],
  seleccionadosAISI: [],
  cantidadEntrevistas: '',
  cantidadEncuestas: '',
  fechaTrabajoCampo: '',
  componenteFuentesPrimarias1: '',
  componenteFuentesPrimarias2: '',
  justificacionAISI: '',
  pagina4DistDpto: '',
  consultora: '',
  entrevistados: [],
  muestra: '',
  universo: '',
  margen: '',
  nameuniverso: '',
  variable: '',
  fuente: '',
  nivel: '',
  detalleEncuesta: '',
  precisionEncuesta: '',
  encuestadoPorcentaje: '',
  noEncuestados: '',
  noResultadoPorcentaje: '',
  influenciaSocialDirecta: '',
  componente1Pagina5: '',
  descripcionTabla: '',
  componente2Pagina5: '',
  tablepagina6: [],
  imagenes: [],
  poblacionSexo: '',
  poblacionEtarios: '',
  codigos: [],
  coordenadasAISD: '',
  altitudAISD: '',
  centroPobladoAISI: '',
  centroPobladoSeleccionadoData: null,
  datosobtenidosAPI: [],
  datosobtenidosAPI2: [],
  detallePET: '',
  detallePetDistrital: '',
  detallePeaDistrital: '',
  detallePeaEmpleo1: '',
  encuestasIndependiente: '',
  encuestasDependientePublica: '',
  encuestasDependientePrivada: '',
  encuestasNoAplica: '',
  detallePeaSituacionEmpleo: '',
  detalleIngresos: '',
  ingresosMensualesPromedio: '',
  ingresosMaximo: '',
  detalleIndiceDesempleo: '',
  component1Data: '',
  myComponent: '',
  myComponent2: '',
  myComponent3: '',
  myComponent4: '',
  detalleCaracteristicasEconomicas: '',
  detalleCaracteristicasEconomicas2: '',
  encuestasNoAplicaPagina9: '',
  tablepagina9: [],
  datosobtenidosAPI3: [],
  viviendasComponent1: '',
  viviendasComponent2: '',
  totalViviendas: '',
  totalViviendasOcupadas: '',
  porcentajeViviendasOcupadas: '',
  imagenes2: [],
  datosobtenidosAPI4: {},
  textoInstitucionalidad: '',
  textoDemografiaAISD: '',
  textoPEA_AISD: '',
  textoActividadesEconomicasAISD: '',
  textoUsoSuelos: '',
  textoRecursosNaturales: '',
  textoIDH: '',
  textoNBI: '',
  textoOrganizacionSocial: '',
  textoFestividades: '',
  textoCostumbres: '',
  textoTurismo: '',
  textoDemografiaAISI: '',
  textoPEA_AISI: '',
  textoActividadesEconomicasAISI: '',
  textoViviendaAISI: '',
  textoServiciosBasicosAISI: '',
  textoTransporteAISI: '',
  textoTelecomunicacionesAISI: '',
  textoInfraestructuraAISI: '',
  textoSaludAISI: '',
  textoEducacionAISI: '',
  textoInfraestructuraEducacionPost: '',
  cantidadEstudiantesEducacionTabla: [],
  ieAyrocaTabla: [],
  ie40270Tabla: [],
  textoAlumnosPorSexoGrado: '',
  alumnosIEAyrocaTabla: [],
  alumnosIE40270Tabla: [],
  totalH: '',
  totalM: '',
  textoNatalidadMortalidad: '',
  natalidadMortalidadTabla: [],
  morbiliadTabla: [],
  morbilidadTabla: [],
  textoMorbilidad: '',
  textoAfiliacionSalud: '',
  afiliacionSaludTabla: [],
  fotografias: [],
  comunidadesCampesinas: [],
  parrafoSeccion1_principal: '',
  parrafoSeccion1_4: '',
  objetivoSeccion1_1: '',
  objetivoSeccion1_2: '',
  parrafoSeccion2_introduccion: '',
  parrafoSeccion2_aisd_completo: '',
  parrafoSeccion2_aisi_completo: '',
  parrafoSeccion3_metodologia: '',
  parrafoSeccion3_fuentes_primarias: '',
  parrafoSeccion3_fuentes_primarias_cuadro: '',
  parrafoSeccion3_fuentes_secundarias: '',
  fuentesSecundariasLista: [
    'Base de Datos de Pueblos Indígenas u Originarios – BDPI.',
    'Censos Nacionales 2017 (XII de Población, VII de Vivienda y III de Comunidades Indígenas) ejecutados por el Instituto Nacional de Estadística e Informática (INEI).',
    'Estadísticas de la Calidad Educativa (ESCALE) de la Unidad de Estadística del Ministerio de Educación (MINEDU).',
    'Ministerio de Energía y Minas (MINEM).',
    'Ministerio de Trabajo y Promoción del Empleo (MTPE).',
    'Ministerio de Transporte y Comunicaciones (MTC).',
    'Observatorio Socio Económico Laboral (OSEL).',
    'Organismo Supervisor de Inversión Privada en Telecomunicaciones – OSIPTEL.',
    'Programa de Naciones Unidas para el Desarrollo – PNUD.',
    'Registro Nacional de Instituciones Prestadoras de Servicios de Salud (RENIPRESS).',
    'Repositorio Digital de Información Multisectorial (REDINFORMA) – MIDIS.',
    'Repositorio Único Nacional de Información en Salud (REUNIS).',
    'Resultados Definitivos de la Población Económicamente Activa 2017 – INEI.',
    'Sistema de Información Distrital para la Gestión Pública – INEI.'
  ],
  parrafoSeccion5_institucionalidad: '',
  parrafoSeccion5_institucionalidad_A1: '',
  parrafoSeccion5_institucionalidad_A2: '',
  parrafoSeccion4_introduccion_aisd: '',
  parrafoSeccion4_comunidad_completo: '',
  parrafoSeccion4_caracterizacion_indicadores: '',
  parrafoSeccion7_situacion_empleo_completo: '',
  parrafoSeccion7_ingresos_completo: '',
  parrafoSeccion8_ganaderia_completo: '',
  parrafoSeccion8_agricultura_completo: '',
  parrafoSeccion10_servicios_basicos_intro: '',
  parrafoSeccion11_transporte_completo: '',
  parrafoSeccion11_telecomunicaciones_completo: '',
  parrafoSeccion12_salud_completo: '',
  parrafoSeccion12_educacion_completo: '',
  parrafoSeccion13_natalidad_mortalidad_completo: '',
  parrafoSeccion13_morbilidad_completo: '',
  parrafoSeccion14_indicadores_educacion_intro: '',
  parrafoSeccion21_aisi_intro_completo: '',
  parrafoSeccion21_centro_poblado_completo: '',
  parrafoSeccion15_religion_completo: '',
  parrafoSeccion16_agua_completo: '',
  parrafoSeccion16_recursos_naturales_completo: '',
  parrafoSeccion30_indicadores_educacion_intro: ''
});
