import { Provider } from '@angular/core';
import { ISectionDataService, IPercentageCalculatorService, ISectionCalculatorService, ITextGeneratorService, IPhotoService, ISeccion2DataService, ISeccion2TextGeneratorService, ISeccion23DataService, ISeccion23TextGeneratorService, ISeccion3DataService, ISeccion3TextGeneratorService, ISeccion10DataService, ISeccion10TextGeneratorService, ISeccion6DataService, ISeccion6TextGeneratorService, ISeccion7DataService, ISeccion7TextGeneratorService, ISeccion8DataService, ISeccion8TextGeneratorService, ISeccion9DataService, ISeccion9TextGeneratorService, ISeccion26DataService, ISeccion26TextGeneratorService, ISeccion12DataService, ISeccion12TextGeneratorService, ISeccion25DataService, ISeccion25TextGeneratorService, ISeccion28DataService, ISeccion28TextGeneratorService, ISeccion29DataService, ISeccion29TextGeneratorService, ISeccion30DataService, ISeccion30TextGeneratorService, ISeccion24DataService, ISeccion24TextGeneratorService, ISeccion22DataService, ISeccion22TextGeneratorService, ISeccion4DataService, ISeccion4TextGeneratorService, ISeccion5DataService, ISeccion5TextGeneratorService } from './domain/interfaces';
import { SectionDataService, PercentageCalculatorService, SectionCalculatorService, TextGeneratorService, PhotoService, Seccion2DataService, Seccion2TextGeneratorService, Seccion23DataService, Seccion23TextGeneratorService, Seccion3DataService, Seccion3TextGeneratorService, Seccion10DataService, Seccion10TextGeneratorService, Seccion6DataService, Seccion6TextGeneratorService, Seccion7DataService, Seccion7TextGeneratorService, Seccion8DataService, Seccion8TextGeneratorService, Seccion9DataService, Seccion9TextGeneratorService, Seccion26DataService, Seccion26TextGeneratorService, Seccion12DataService, Seccion12TextGeneratorService, Seccion25DataService, Seccion25TextGeneratorService, Seccion28DataService, Seccion28TextGeneratorService, Seccion29DataService, Seccion29TextGeneratorService, Seccion30DataService, Seccion30TextGeneratorService, Seccion24DataService, Seccion24TextGeneratorService, Seccion22DataService, Seccion22TextGeneratorService, Seccion4DataService, Seccion4TextGeneratorService, Seccion5DataService, Seccion5TextGeneratorService } from './infrastructure/services';

export const SECTION_PROVIDERS: Provider[] = [
  { provide: ISectionDataService, useClass: SectionDataService },
  { provide: IPercentageCalculatorService, useClass: PercentageCalculatorService },
  { provide: ISectionCalculatorService, useClass: SectionCalculatorService },
  { provide: ITextGeneratorService, useClass: TextGeneratorService },
  { provide: IPhotoService, useClass: PhotoService },
  { provide: ISeccion2DataService, useClass: Seccion2DataService },
  { provide: ISeccion2TextGeneratorService, useClass: Seccion2TextGeneratorService },
  { provide: ISeccion23DataService, useClass: Seccion23DataService },
  { provide: ISeccion23TextGeneratorService, useClass: Seccion23TextGeneratorService },
  { provide: ISeccion3DataService, useClass: Seccion3DataService },
  { provide: ISeccion3TextGeneratorService, useClass: Seccion3TextGeneratorService },
  { provide: ISeccion10DataService, useClass: Seccion10DataService },
  { provide: ISeccion10TextGeneratorService, useClass: Seccion10TextGeneratorService },
  { provide: ISeccion6DataService, useClass: Seccion6DataService },
  { provide: ISeccion6TextGeneratorService, useClass: Seccion6TextGeneratorService },
  { provide: ISeccion7DataService, useClass: Seccion7DataService },
  { provide: ISeccion7TextGeneratorService, useClass: Seccion7TextGeneratorService },
  { provide: ISeccion8DataService, useClass: Seccion8DataService },
  { provide: ISeccion8TextGeneratorService, useClass: Seccion8TextGeneratorService },
  { provide: ISeccion9DataService, useClass: Seccion9DataService },
  { provide: ISeccion9TextGeneratorService, useClass: Seccion9TextGeneratorService },
  { provide: ISeccion26DataService, useClass: Seccion26DataService },
  { provide: ISeccion26TextGeneratorService, useClass: Seccion26TextGeneratorService },
  { provide: ISeccion12DataService, useClass: Seccion12DataService },
  { provide: ISeccion12TextGeneratorService, useClass: Seccion12TextGeneratorService },
  { provide: ISeccion25DataService, useClass: Seccion25DataService },
  { provide: ISeccion25TextGeneratorService, useClass: Seccion25TextGeneratorService },
  { provide: ISeccion28DataService, useClass: Seccion28DataService },
  { provide: ISeccion28TextGeneratorService, useClass: Seccion28TextGeneratorService },
  { provide: ISeccion29DataService, useClass: Seccion29DataService },
  { provide: ISeccion29TextGeneratorService, useClass: Seccion29TextGeneratorService },
  { provide: ISeccion30DataService, useClass: Seccion30DataService },
  { provide: ISeccion30TextGeneratorService, useClass: Seccion30TextGeneratorService },
  { provide: ISeccion24DataService, useClass: Seccion24DataService },
  { provide: ISeccion24TextGeneratorService, useClass: Seccion24TextGeneratorService },
  { provide: ISeccion22DataService, useClass: Seccion22DataService },
  { provide: ISeccion22TextGeneratorService, useClass: Seccion22TextGeneratorService },
  { provide: ISeccion4DataService, useClass: Seccion4DataService },
  { provide: ISeccion4TextGeneratorService, useClass: Seccion4TextGeneratorService },
  { provide: ISeccion5DataService, useClass: Seccion5DataService },
  { provide: ISeccion5TextGeneratorService, useClass: Seccion5TextGeneratorService }
];
